apimServiceName: apim-mmm-apim-ws-prod
namedValues:
- name: TopSecret
  properties:
    keyVault:
      identityClientId: c96aa7c5-4222-40df-84f5-1696f2116d75
      secretIdentifier: https://kv-mmm-apim-ws-prod.vault.azure.net/secrets/TopSecret
- name: 6716c1e746346116c4345b53
  properties:
    value: '{#appInsightsKey1#}'
- name: 67155e8646346116c43456add
  properties:
    value: '{#appInsightsKey2#}'
