openapi: 3.0.1
info:
  title: Basic Calculator
  description: Arithmetics is just a call away!
  version: '2024-10-21'
servers:
  - url: https://apim-mmm-apim-ws-dev.azure-api.net/calc/2024-10-21
paths:
  /add:
    get:
      summary: Add two integers
      description: Produces a sum of two numbers.
      operationId: 671680f146346116c43459b2
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
      responses:
        '200':
          description: 
  /sub:
    get:
      summary: Subtract two integers
      description: Produces a difference between two numbers.
      operationId: 671680f146346116c43459b3
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
      responses:
        '200':
          description: 
  /mul:
    get:
      summary: Multiply two integers
      description: Produces a product of two numbers.
      operationId: 671680f146346116c43459b4
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
      responses:
        '200':
          description: 
  /div:
    get:
      summary: Divide two integers
      description: Produces a quotient of two numbers.
      operationId: 671680f146346116c43459b5
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
            default: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]